### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/pre-project-example#1]
### 만들고자 하는 기능이 무엇인가요?
Todo 추가 기능

### 해당 기능을 구현하기 위해 할 일은 무엇인가요?
- [x] input 필드 만들기
- [x] 추가 버튼 만들기
- [x] 추가된 todo가 보여질 공간 만들기
- [x] 버튼 동작 함수 만들기

### 예상 작업 시간
3h
