### ISSUE TITLE
[Bare - task] Todo 추가 기능 구현

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/pre-project-example#1]
## 설명
Todo 추가 기능을 구현합니다.

## 체크리스트
- [x] 추가할 내용을 입력할 input 필드 만들기
- [x] 버튼과 핸들러 함수 만들기
- [x] 추가된 Todo가 보여질 공간 만들기

## 예상시간
2h
