### ISSUE TITLE
[Bare - task] Todo 삭제 기능 구현

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/pre-project-example#2]
## 설명
Todo 삭제 기능을 구현합니다.

## 체크리스트
- [x] 삭제 버튼 만들기
- [ ] 버튼 클릭 함수 만들기
- [ ] id 파라미터로 서버에 delete 요청 보내기

## 예상시간
2h
