### ISSUE TITLE
[Bare - task] Todo 추가하기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/pre-project-example#2]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 추가 기능

### 해당 기능을 구현하기 위해 할 일은 무엇인가요?
 - [x] input 필드 만들기
 - [x] 추가 버튼 만들기
 - [x] 버튼 동작 함수 만들기
 - [x] 추가된 task가 보여질 공간 만들기

### 예상 작업 시간
2h
