### ISSUE TITLE
[Bare - task] Todo 삭제하기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/pre-project-example#3]
### 만들고자 하는 기능이 무엇인가요?
Todo 삭제 기능

### 해당 기능을 구현하기 위해 할 일은 무엇인가요?
 - [x] 삭제 버튼 만들기
 - [x] 버튼 동작 함수 만들기
 - [x] id 파라미터로 서버에 삭제 요청 보내기
 - [x] 업데이트된 데이터로 다시 렌더링하기

### 예상 작업 시간
2h
